CREATE TABLE PRODUCTOS (
    ID NUMBER(19,0) NOT NULL,
    DESCRIPCION VARCHAR2(255 CHAR),
    NOMBRE VARCHAR2(255 CHAR),
    PRECIO FLOAT,
    STOCK NUMBER(10,0),
    CONSTRAINT PRODUCTOS_PK PRIMARY KEY (ID)
);